import { describe, expect, it } from 'vitest';
import { inspectImageHeader, validateDimensions, validateSettings, imageFilename } from './images';
import type { ImageSettings } from './images';
const fixtures = {"transparent.png": "iVBORw0KGgoAAAANSUhEUgAAAFAAAAAoCAYAAABpYH0BAAAAf0lEQVR4nO3QsRFAQAAAQa8WgSKUrwiBXuhAcgFmdiu4uXGu2zV92HLs4+2GJ/PbAX9nYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgdAOR6QRQqsKy5AAAAABJRU5ErkJggg==", "transparent.webp": "UklGRiwAAABXRUJQVlA4TB8AAAAvT8AJEA8wKMM9PPMf8AYzbduUP+lh2OdE9D+uavAFAA==", "small.jpg": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAoAFADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDn6KKK80/TgooooAK8fr2CvH66cP1PmOI/+XXz/QKKKK6T5gKKKKAPYKKKK80/TgooooAK8fr2CvH66cP1PmOI/wDl18/0Ciiiuk+YCiiigD2CiiivNP04KKKKACvH6KK6cP1PmOI/+XXz/QKKKK6T5gKKKKAP/9k=", "animated.png": "iVBORw0KGgoAAAANSUhEUgAAAFAAAAAoCAYAAABpYH0BAAAACGFjVEwAAAACAAAAAPONk3AAAAAaZmNUTAAAAAAAAABQAAAAKAAAAAAAAAAAAAEACgAALWBOWwAAAH9JREFUeJzt0LERQEAAAEGvFoEilK8IgV7oQHIBZnYruLlxrts1fdhy7OPthifz2wF/Z2BkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYHQDkekEUKrCsuQAAAAaZmNUTAAAAAEAAABQAAAAKAAAAAAAAAAAAAEACgAAthOkjwAAAHlmZEFUAAAAAnic7dBBDYAwAMDAMTUThmy8MA/rg5DcKWh6rft5B8fm1wF/Z2BkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYGRgZGBkYLQBhoACt/6aQsYAAAAASUVORK5CYII=", "animated.webp": "UklGRvoAAABXRUJQVlA4WAoAAAACAAAATwAAJwAAQU5JTQYAAAAAAAAAAABBTk1GXgAAAAAAAAAAACcAACcAAGQAAAJWUDggRgAAALADAJ0BKigAKAA+bTaYSKQjIqEjiACADYlnAHYABD8CNj03xzgAAP7tBy/+IXeyHP//7aH/60P/1of9R3/ATHRfwExYAABBTk1GaAAAAAAAAAAAAE8AACcAAGQAAABWUDggUAAAAFQEAJ0BKlAAKAA+bTKSSQIiAADYlpBigH7/idAfgACRcaslTYugXOIZ2QAA/u1N3//6gz5aHy0P2FP//izkYjs83SuDCXnr3g6HGD7QIAAA"};
function buffer(name: keyof typeof fixtures) { const bytes = Uint8Array.from(atob(fixtures[name]), c => c.charCodeAt(0)); return bytes.buffer; }
const settings: ImageSettings = { width: 80, height: 40, format: 'image/png', quality: 0.85, background: '#ffffff' };
describe('Image input validation', () => {
  it('reads actual PNG, JPG and lossless WebP headers', () => {
    for (const [name, format] of [['transparent.png', 'image/png'], ['small.jpg', 'image/jpeg'], ['transparent.webp', 'image/webp']] as const) expect(inspectImageHeader(buffer(name))).toEqual({ width: 80, height: 40, format });
  });
  it('rejects animated PNG and WebP before decoding', () => { for (const name of ['animated.png', 'animated.webp'] as const) expect(() => inspectImageHeader(buffer(name))).toThrow('Animated'); });
  it('rejects disguised SVG and truncated files', () => { expect(() => inspectImageHeader(new TextEncoder().encode('<svg/>').buffer)).toThrow('valid'); expect(() => inspectImageHeader(buffer('transparent.png').slice(0, 25))).toThrow('valid'); });
  it('rejects oversized dimensions before image decoding', () => { const data = buffer('transparent.png'); new DataView(data).setUint32(16, 9000); expect(() => inspectImageHeader(data)).toThrow('dimensions'); });
  it('checks WebP bitstream dimensions even with a smaller extended canvas header', () => {
    const simple = new Uint8Array(buffer('transparent.webp')); const data = new Uint8Array(simple.length + 18);
    data.set(simple.slice(0, 12)); data.set(new TextEncoder().encode('VP8X'), 12); const view = new DataView(data.buffer);
    view.setUint32(16, 10, true); data[24] = 79; data[27] = 39; data.set(simple.slice(12), 30); view.setUint32(4, data.length - 8, true);
    const p = 39; const bits = view.getUint32(p, true); view.setUint32(p, (bits & ~16383) | 8999, true);
    expect(() => inspectImageHeader(data.buffer)).toThrow('dimensions');
  });
  it('rejects a PNG chunk whose length exceeds the file', () => { const data = buffer('transparent.png'); new DataView(data).setUint32(33, 4294967295); expect(() => inspectImageHeader(data)).toThrow('valid'); });
});
describe('Image output limits', () => {
  it('rejects zero, fractional, infinite and excessive pixel allocations', () => { for (const [w,h] of [[0,1],[1.5,1],[Infinity,1],[8000,8000],[NaN,1]]) expect(() => validateDimensions(w,h)).toThrow(); });
  it('rejects crops outside the source image', () => { expect(() => validateSettings({ ...settings, crop: { x: 50, y: 0, width: 40, height: 40 } }, 80, 40)).toThrow('crop'); expect(() => validateSettings({ ...settings, crop: { x: -1, y: 0, width: 40, height: 40 } }, 80, 40)).toThrow('crop'); });
  it('rejects invalid quality and unusable compression targets', () => { expect(() => validateSettings({ ...settings, quality: NaN }, 80, 40)).toThrow(); expect(() => validateSettings({ ...settings, targetBytes: 2048 }, 80, 40)).toThrow('target'); expect(() => validateSettings({ ...settings, format: 'image/jpeg', targetBytes: NaN }, 80, 40)).toThrow('target'); });
  it('accepts a valid crop and JPG target', () => expect(() => validateSettings({ ...settings, format: 'image/jpeg', targetBytes: 2048, crop: { x: 0, y: 0, width: 40, height: 40 } }, 80, 40)).not.toThrow());
  it('uses the encoded format for safe download names', () => { expect(imageFilename('photo.PNG', 'image/jpeg')).toBe('photo-filenest.jpg'); expect(imageFilename('../../fake.png', 'image/webp')).not.toContain('/'); });
});
