import { useEffect, useRef, useState } from 'react';
import { checkText } from '../lib/data-tools';
import type { CsvReport } from '../lib/data-tools';
export default function DataWorkbench({ mode }: { mode: 'csv' | 'json' }) {
  const [left, setLeft] = useState(''), [right, setRight] = useState(''), [key, setKey] = useState('');
  const [trim, setTrim] = useState(false), [ignoreCase, setIgnoreCase] = useState(false);
  const [jsonMode, setJsonMode] = useState<'pretty' | 'minify' | 'validate'>('pretty'), [indent, setIndent] = useState<'2' | '4' | 'tab'>('2');
  const [result, setResult] = useState<string | CsvReport | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [status, setStatus] = useState('');
  const worker = useRef<Worker | null>(null), timer = useRef<ReturnType<typeof setTimeout> | null>(null), generation = useRef(0);
  const files = [useRef<HTMLInputElement>(null), useRef<HTMLInputElement>(null)];
  useEffect(() => () => { worker.current?.terminate(); if (timer.current) clearTimeout(timer.current); generation.current++; }, []);
  function stop() { generation.current++; worker.current?.terminate(); worker.current = null; if (timer.current) clearTimeout(timer.current); timer.current = null; setBusy(false); }
  function invalidate() { stop(); setResult(null); setError(''); setStatus(''); }
  function edit(value: string, side: number) { invalidate(); try { checkText(value); side ? setRight(value) : setLeft(value); } catch (e) { setError((e as Error).message); } }
  async function load(file: File | undefined, side: number) { if (!file) return; invalidate(); const version = generation.current; try { if (file.size > 1_000_000) throw new Error('Choose a text file up to 1 MB.'); const value = await file.text(); if (generation.current === version) edit(value, side); } catch (e) { if (generation.current === version) setError((e as Error).message); } }
  function sample() { invalidate(); if (mode === 'csv') { setLeft('id,name,city\n001,Adhi,Mangaluru\n002,Maya,Udupi\n003,Ravi,Karwar'); setRight('id,name,city\n002,Maya,Manipal\n001,Adhi,Mangaluru\n004,Neha,Goa'); setKey('id'); } else setLeft('{"name":"FileNest","id":9007199254740993,"tools":["PDF","Images"],"local":true}'); }
  function process() {
    invalidate(); if (!left.trim() || (mode === 'csv' && !right.trim())) { setError(mode === 'csv' ? 'Add both CSV inputs, including their header rows.' : 'Add JSON before processing.'); return; }
    try {
      setBusy(true); const w = new Worker(new URL('../workers/data-tools.worker.ts', import.meta.url), { type: 'module' }); worker.current = w;
      w.onmessage = event => { if (worker.current !== w) return; stop(); if (event.data.error) setError(event.data.error); else { setResult(event.data.result); setStatus(mode === 'csv' ? 'Comparison ready.' : jsonMode === 'validate' ? 'Validation complete.' : 'JSON ready.'); } };
      w.onerror = () => { if (worker.current === w) { stop(); setError('Processing failed. Try a smaller input.'); } };
      timer.current = setTimeout(() => { stop(); setError('This job took too long. Try smaller files.'); }, 10000);
      w.postMessage({ mode, left, right, key, trim, ignoreCase, jsonMode, indent });
    } catch { stop(); setError('Your browser could not start this tool. Try an updated browser.'); }
  }
  const text = typeof result === 'string' ? result : JSON.stringify(result, null, 2);
  function download() { const url = URL.createObjectURL(new Blob([text], { type: jsonMode === 'validate' && mode === 'json' ? 'text/plain;charset=utf-8' : 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = mode === 'csv' ? 'csv-comparison-filenest.json' : jsonMode === 'validate' ? 'json-validation-filenest.txt' : 'formatted-filenest.json'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 10000); }
  async function copy() { try { await navigator.clipboard.writeText(text); setStatus('Copied to clipboard.'); } catch { setError('Clipboard unavailable. Select the result or download it.'); } }
  return <div className="workbench"><div className="workbench-toolbar"><span className="local-pill"><i /> Files stay on this device</span><div><button className="subtle-button" onClick={sample}>Load example</button><button className="subtle-button" onClick={() => { invalidate(); setLeft(''); setRight(''); }}>Clear all</button></div></div>
    <div className={`editor-grid ${mode === 'csv' ? 'two-column' : ''}`}>{(mode === 'csv' ? [0, 1] : [0]).map(side => <div className="editor-panel" key={side}><div className="panel-heading"><label htmlFor={`data-${side}`}>{mode === 'csv' ? side ? 'Updated CSV' : 'Original CSV' : 'JSON input'}</label><button onClick={() => files[side].current?.click()}>Open file ↗</button></div><input ref={files[side]} type="file" className="visually-hidden" accept={mode === 'csv' ? '.csv,.tsv,.txt' : '.json,.txt'} onChange={e => { void load(e.target.files?.[0], side); e.target.value = ''; }} /><textarea id={`data-${side}`} value={side ? right : left} spellCheck={false} placeholder={mode === 'csv' ? 'id,name\n001,Adhi' : '{"name":"FileNest"}'} onChange={e => edit(e.target.value, side)} /><div className="editor-meta">{(side ? right : left).length.toLocaleString()} characters<span>UTF-8 text</span></div></div>)}</div>
    <fieldset className="image-settings" disabled={busy}><legend>{mode === 'csv' ? 'Comparison settings' : 'JSON settings'}</legend><div className="image-settings-grid">{mode === 'csv' ? <><label>Key column (optional)<input type="text" value={key} placeholder="e.g. id; blank matches row position" onChange={e => { invalidate(); setKey(e.target.value); }} /></label><label className="image-check"><input type="checkbox" checked={trim} onChange={e => { invalidate(); setTrim(e.target.checked); }} /> Ignore edge whitespace in values</label><label className="image-check"><input type="checkbox" checked={ignoreCase} onChange={e => { invalidate(); setIgnoreCase(e.target.checked); }} /> Ignore case in values</label></> : <><label>Action<select aria-label="Action" value={jsonMode} onChange={e => { invalidate(); setJsonMode(e.target.value as typeof jsonMode); }}><option value="pretty">Beautify</option><option value="minify">Minify</option><option value="validate">Validate only</option></select></label>{jsonMode === 'pretty' && <label>Indentation<select aria-label="Indentation" value={indent} onChange={e => { invalidate(); setIndent(e.target.value as typeof indent); }}><option value="2">2 spaces</option><option value="4">4 spaces</option><option value="tab">Tabs</option></select></label>}</>}</div><p className="image-note">{mode === 'csv' ? 'CSV/TSV exports only, not XLSX files. Headers and key values match exactly; key values must be unique. Column order is ignored. Data row numbers exclude the header. Blank rows are skipped; original cell values are kept in the report. Long cells and large reports have shortened previews; download for the full content.' : 'Standard JSON only: no comments or trailing commas. Formatting preserves original number spelling, string escapes, key order and duplicate keys. Validation checks syntax, not a schema.'}</p></fieldset>
    <div className="action-row"><span className="image-note">Local processing · up to 1 MB per input</span><div className="action-buttons">{busy ? <button className="secondary-button" onClick={() => { stop(); setStatus('Processing cancelled.'); }}>Cancel processing</button> : <button className="primary-button" onClick={process}>{mode === 'csv' ? 'Compare CSV' : 'Process JSON'} ↗</button>}</div></div>
    <div className="feedback" aria-live="polite">{error && <p role="alert" className="error-message">{error}</p>}{!error && (busy || status) && <p className="status-message">{busy ? 'Working on your device…' : status}</p>}</div>
    {result !== null && <section className="result-panel"><div className="panel-heading"><h2>{mode === 'csv' ? 'Your changes' : 'Your result'}</h2><div><button onClick={() => { void copy(); }}>Copy</button><button onClick={download}>Download result ↗</button></div></div>{typeof result === 'string' ? <pre className="data-result">{result.slice(0, 100000)}{result.length > 100000 ? '\n[Preview shortened. Download for the complete result.]' : ''}</pre> : <><p className="comparison-summary">{result.changes.filter(c => c.type === 'added').length} added · {result.changes.filter(c => c.type === 'removed').length} removed · {result.changes.filter(c => c.type === 'changed').length} changed · {result.unchanged} unchanged rows</p>{(result.columnsAdded.length > 0 || result.columnsRemoved.length > 0) && <p className="comparison-summary">Columns added: {result.columnsAdded.join(', ') || 'none'} · removed: {result.columnsRemoved.join(', ') || 'none'}</p>}{!result.changes.length && !result.columnsAdded.length && !result.columnsRemoved.length ? <p className="identical">No differences with these settings.</p> : <div className="json-changes">{result.changes.slice(0, 200).map((change, i) => <div className="json-change" key={i}><div><span className={`change-label ${change.type}`}>{change.type}</span><code>{change.key}</code><span>{change.originalRow ? `original row ${change.originalRow}` : ''}{change.updatedRow ? ` · updated row ${change.updatedRow}` : ''}</span></div><pre className="data-result">{JSON.stringify(change.cells ?? change.before ?? change.after, null, 2).slice(0, 5000)}</pre></div>)}{result.changes.length > 200 && <p className="comparison-summary">Showing 200 changed rows. Download for the complete report.</p>}</div>}</>}</section>}
  </div>;
}
