import { useEffect, useRef, useState } from 'react';
import { MAX_IMAGE_BYTES, formatBytes } from '../lib/images';
type Result = { blob: Blob; urls: string[]; width: number; height: number; changed: number; total: number; meanDifference: number };
export default function ImageCompare() {
  const [files, setFiles] = useState<(File | null)[]>([null, null]), [threshold, setThreshold] = useState(0), [view, setView] = useState('side'), [slider, setSlider] = useState(50);
  const [result, setResult] = useState<Result | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [status, setStatus] = useState('');
  const pickers = [useRef<HTMLInputElement>(null), useRef<HTMLInputElement>(null)]; const worker = useRef<Worker | null>(null), timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => () => { worker.current?.terminate(); if (timer.current) clearTimeout(timer.current); }, []);
  useEffect(() => () => { result?.urls.forEach(url => URL.revokeObjectURL(url)); }, [result]);
  function stop() { worker.current?.terminate(); worker.current = null; if (timer.current) clearTimeout(timer.current); timer.current = null; setBusy(false); }
  function invalidate() { stop(); setResult(null); setError(''); setStatus(''); }
  function choose(file: File | undefined, index: number) { if (!file) return; invalidate(); const next = [...files]; next[index] = null; if (!file.size || file.size > MAX_IMAGE_BYTES) setError('Choose a still image up to 15 MB.'); else next[index] = file; setFiles(next); }
  function process() {
    invalidate(); if (files.some(f => !f)) { setError('Choose an original and an updated image.'); return; }
    try {
      setBusy(true); const w = new Worker(new URL('../workers/image-compare.worker.ts', import.meta.url), { type: 'module' }); worker.current = w;
      w.onmessage = event => { if (worker.current !== w) return; stop(); if (event.data.error) setError(event.data.error); else { setResult({ ...event.data, urls: event.data.previews.map((b: Blob) => URL.createObjectURL(b)) }); setStatus('Comparison ready.'); } };
      w.onerror = () => { if (worker.current === w) { stop(); setError('Image comparison failed. Try smaller images or an updated browser.'); } };
      timer.current = setTimeout(() => { stop(); setError('This comparison took too long. Resize both images first.'); }, 30000); w.postMessage({ files, threshold });
    } catch { stop(); setError('Your browser could not start this image tool. Try an updated browser.'); }
  }
  function download() { if (!result) return; const url = URL.createObjectURL(result.blob), a = document.createElement('a'); a.href = url; a.download = 'image-difference-filenest.png'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 10000); }
  return <div className="workbench"><div className="workbench-toolbar"><span className="local-pill"><i /> Files stay on this device</span><button className="subtle-button" onClick={() => { invalidate(); setFiles([null, null]); }}>Clear images</button></div>
    <div className="image-previews">{files.map((file, i) => <div className="compare-picker" key={i}><label htmlFor={`compare-image-${i}`}>{i ? 'Updated image' : 'Original image'}</label><input id={`compare-image-${i}`} ref={pickers[i]} type="file" className="visually-hidden" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp" onChange={e => { choose(e.target.files?.[0], i); e.target.value = ''; }} /><button className="secondary-button" onClick={() => pickers[i].current?.click()}>Choose {i ? 'updated' : 'original'} image ↗</button><p className="image-filename">{file ? `${file.name} · ${formatBytes(file.size)}` : 'Still JPG, PNG or WebP · up to 15 MB'}</p></div>)}</div>
    <fieldset className="image-settings" disabled={busy}><legend>Comparison settings</legend><label>Pixel threshold: {threshold}<input aria-label="Pixel threshold" type="range" min="0" max="255" value={threshold} onChange={e => { invalidate(); setThreshold(Number(e.target.value)); }} /></label><p className="image-note">Images must have equal dimensions after EXIF orientation. Transparent pixels are composited on white. A pixel changes when any RGB channel differs by more than the threshold. This is a pixel comparison; compression and browser colour handling can affect results.</p></fieldset>
    <div className="action-row"><span className="image-note">Two images · up to 6 megapixels each</span><div className="action-buttons">{busy ? <button className="secondary-button" onClick={() => { stop(); setStatus('Processing cancelled.'); }}>Cancel processing</button> : <button className="primary-button" disabled={files.some(f => !f)} onClick={process}>Compare images ↗</button>}{result && <button className="secondary-button" onClick={download}>Download difference ↗</button>}</div></div>
    <div className="feedback" aria-live="polite">{error && <p role="alert" className="error-message">{error}</p>}{!error && (busy || status) && <p className="status-message">{busy ? 'Comparing on your device…' : status}</p>}</div>
    {result && <section className="result-panel"><div className="panel-heading"><h2>Your comparison</h2><span>{result.width} × {result.height}</span></div><p className="comparison-summary">{result.changed.toLocaleString()} of {result.total.toLocaleString()} pixels changed ({(result.changed / result.total * 100).toFixed(2)}%) · mean RGB difference {result.meanDifference.toFixed(2)}%</p><div className="compare-view-controls"><label>View<select aria-label="View" value={view} onChange={e => setView(e.target.value)}><option value="side">Side by side</option><option value="overlay">Overlay slider</option><option value="diff">Difference mask</option></select></label>{view === 'overlay' && <label>Updated image revealed: {slider}%<input aria-label="Overlay slider" type="range" min="0" max="100" value={slider} onChange={e => setSlider(Number(e.target.value))} /></label>}</div>{view === 'side' ? <div className="image-previews"><figure><figcaption>Original</figcaption><img src={result.urls[0]} alt="Original comparison image" /></figure><figure><figcaption>Updated</figcaption><img src={result.urls[1]} alt="Updated comparison image" /></figure></div> : view === 'overlay' ? <div className="image-overlay"><img src={result.urls[0]} alt="Original beneath updated image" /><img className="overlay-updated" src={result.urls[1]} alt="Updated image overlay" style={{ clipPath: `inset(0 ${100 - slider}% 0 0)` }} /><span style={{ left: `${slider}%` }} /></div> : <figure className="compare-difference"><img src={result.urls[2]} alt="Changed pixels highlighted in pink" /><figcaption>Pink marks changed pixels. Unchanged pixels appear as a faded grayscale image.</figcaption></figure>}</section>}
  </div>;
}
